### Test student insert
POST http://localhost:8080/students/Add
Content-Type: application/json

{
  "Id": "234342526",
  "firstName": "Mai",
  "lastName": "Eden",
  "grade": "6,2"
}

###
GET http://localhost:8080/students/get/214332552

###
POST http://localhost:8080/teacher/add
Content-Type: application/json

{
  "Id": "214332552",
  "firstName": "Lea",
  "lastName": "Levy",
  "grade": "6,2"
}

###
GET http://localhost:8080/teacher/get/214342552

###
GET http://localhost:8080/teacher/getStudents/214332552

### cordinates
###
POST http://localhost:8080/Locations/Add
Content-Type: application/json

{
  "ID": "214332552",
  "Coordinates": {
    "Longitude": {"Degrees": "34", "Minutes": "46", "Seconds": "44"},
    "Latitude": {"Degrees": "32", "Minutes": "5", "Seconds": "23"}
  },
  "Time": "2024-12-05T15:30:00Z"
}

###
GET http://localhost:8080/Locations/get/214332552